name: Build and deploy website

on:
  push:
    branches: [ main ]
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Fetch GitHub repositories data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub Actions
        run: |
          mkdir -p assets/data

          echo "Fetching joe-lannan repositories"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/users/joe-lannan/repos?sort=size&direction=desc&per_page=100" \
               > assets/data/joe-lannan-repos.json

          echo "Fetching koinslot-inc repositories"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/users/koinslot-inc/repos?sort=size&direction=desc&per_page=100" \
               > assets/data/koinslot-inc-repos.json

          # Combine repositories into one file
          echo "Combining repositories data"
          jq -s 'add | sort_by(.size) | reverse' assets/data/joe-lannan-repos.json assets/data/koinslot-inc-repos.json > assets/data/github-repos.json

          # Create timestamp
          echo "{\"updated_at\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > assets/data/repos-updated.json

          echo "Repository data fetched successfully"

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages